INSERT INTO relationships VALUES(NULL,'Depende de', 'Usado por','',NOW(), NOW());
INSERT INTO relationships VALUES(NULL,'Usa', 'Usado por','',NOW(), NOW());
INSERT INTO relationships VALUES(NULL,'Envia datos a', 'Recibe datos de','',NOW(), NOW());
INSERT INTO relationships VALUES(NULL,'Corre', 'Corre en','',NOW(), NOW());
INSERT INTO relationships VALUES(NULL,'Conectado a', 'Conectado a','',NOW(), NOW());
INSERT INTO relationships VALUES(NULL,'Suscribe', 'Suscrito a','',NOW(), NOW());
INSERT INTO relationships VALUES(NULL,'Impacta', 'Impactado por','',NOW(), NOW());
INSERT INTO relationships VALUES(NULL,'Soporta', 'Soportado por','',NOW(), NOW());
INSERT INTO relationships VALUES(NULL,'Autor de', 'Escrito por','',NOW(), NOW());
INSERT INTO relationships VALUES(NULL,'Hospedado en', 'Hospeda','',NOW(), NOW());
INSERT INTO relationships VALUES(NULL,'Habilita', 'Es hailitado por','',NOW(), NOW());
INSERT INTO relationships VALUES(NULL,'Incluye', 'Es miembro de','',NOW(), NOW());
INSERT INTO relationships VALUES(NULL,'Contiene', 'En Rack','',NOW(), NOW());
INSERT INTO relationships VALUES(NULL,'Intercambia datos con', 'Intercambia datos con','',NOW(), NOW());
INSERT INTO relationships VALUES(NULL,'Administrado por', 'Administra','',NOW(), NOW());
INSERT INTO relationships VALUES(NULL,'Virtualizado por', 'Virtualiza','',NOW(), NOW());
INSERT INTO relationships VALUES(NULL,'Respaldado por', 'Respaldado por','',NOW(), NOW());
INSERT INTO relationships VALUES(NULL,'Parte de', 'Parte de','',NOW(), NOW());
INSERT INTO relationships VALUES(NULL,'Adjunto a', 'Contiene','',NOW(), NOW());
